---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
  labels:
    app: label-studio
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: label-studio
  template:
    metadata:
      labels:
        app: label-studio
    spec:
      containers:
      - name: label-studio
        {{ with .Values.deployment.image -}}
        image: {{ .name }}:{{ .tag }}
        {{ end -}}
        ports:
        - containerPort: 8080
        env:
        # https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-with-a-host-and-sub-path
        # Note without docker-compose, this requires NGINX in-front to rewrite the path
        - name: LABEL_STUDIO_HOST
          value: "{{ .Values.ingress.host }}{{ .Values.ingress.path }}"
